services:
  # LITESTAR BACKEND 
  backend:
    container_name: aestelo_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
    restart: unless-stopped
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./backend/app
          target: /app/app
          ignore:
            - __pycache__/
            - .pytest_cache/
        - action: rebuild
          path: .env
        - action: rebuild
          path: ./backend/pyproject.toml
        - action: rebuild
          path: ./backend/uv.lock
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

# BG Workers
  workers:
    container_name: aestelo_workers
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: dev
    command: litestar workers run
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
    networks:
      - aestelo_network
      

  # POSTGRES DATABASE (with postgis)
  db:
    image: postgis/postgis:18-3.6
    container_name: aestelo_db
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DB}
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER} -d ${DB_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # REACT FRONTEND 
  frontend:
    container_name: aestelo_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules
            - dist/
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/pnpm-lock.yaml
        - action: rebuild
          path: .env
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules 
    depends_on:
      - backend
    env_file:
      - .env
  
  #  REDIS
  redis:
    image: redis:7-alpine
    container_name: aestelo_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${BROKER_REDIS_PASSWORD}
    environment:
      REDIS_URL: ${BROKER_REDIS}
      REDIS_PASSWORD: ${BROKER_REDIS_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data 
    networks:
      - aestelo_network
  
  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    container_name: aestelo_redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    depends_on:
      - redis

volumes:
  redis_data:
    name: aestelo_redis_data
  postgres_data:
    name: aestelo_db
  redis-insight:
    name: aestelo_redis-insight
  backend_venv:
    name: aestelo_backend_venv
  frontend_node_modules:
    name: aestelo_frontend_node_modules
  aestelo_network:
    driver: bridge