services:
  # --- FLASK BACKEND ---
  backend:
    container_name: aestelo_backend
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - temp_uploads:/app/uploads_tmp 
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - UPLOAD_FOLDER=/app/uploads_tmp 
    env_file:
      - ./backend/env_backend/.env.backend_cloudflare
      - ./backend/env_backend/.env.backend_supabase
      - ./backend/env_backend/.env.backend_sightengine
      - ./backend/env_backend/.env.backend_sendgrid
      - ./backend/env_backend/.env.backend_celery
      - ./backend/env_backend/.env.development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - redis

  #---- CELERY ----#
  celery_worker:
    build: ./backend
    command: python -m watchdog.watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A make_celery.celery_app worker --loglevel=info
    env_file:
      - ./backend/env_backend/.env.backend_celery
    depends_on:
      - backend
      - redis
    volumes:
      - ./backend:/app
      - temp_uploads:/app/uploads_tmp 
    environment:
      - UPLOAD_FOLDER=/app/uploads_tmp

  # --- REACT FRONTEND ---
  frontend:
    container_name: aestelo_frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules 
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
  
  #--- REDIS ---#
  redis:
    image: redis/redis-stack:latest
    container_name: aestelo_redis_stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data 
  
  flower:
    build: ./backend
    container_name: aestelo_flower
    
    command: celery -A make_celery.celery_app flower --port=5555
    
    ports:
      - "5555:5555"
    env_file:
      - ./backend/env_backend/.env.backend_celery
    depends_on:
      - redis
      - celery_worker
    volumes:
      - ./backend:/app

volumes:

  node_modules:
    name: aestelo_frontend_node_modules

  temp_uploads:
    name: aestelo_backend_temp_uploads

  redis_data:
    name: aestelo_redis_data