services:
  # --- LITESTAR BACKEND --- #
  backend:
    container_name: aestelo_backend
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
    command: litestar --app app.main:app run --reload --host 0.0.0.0 --port 8000
    restart: unless-stopped
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  workers:
    container_name: aestelo_workers
    build:
      context: ./backend
    command: litestar --app app.main:app workers run
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/.venv
      

  # --- POSTGRES DATABASE ---#  
  db:
    image: postgis/postgis:18-3.6
    container_name: aestelo_db
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_POSTGRES_DB}
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER} -d ${DB_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- REACT FRONTEND ---
  frontend:
    container_name: aestelo_frontend
    build: 
      context: ./frontend
      target: development
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    environment:
      NODE_ENV: ${VITE_ENV}
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend
    env_file:
      - .env
  
  #--- REDIS ---#
  redis:
    image: redis:7-alpine
    container_name: aestelo_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${BROKER_REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${BROKER_REDIS_PASSWORD}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/data 
  
  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    container_name: aestelo_redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    depends_on:
      - redis

volumes:
  redis_data:
    name: aestelo_redis_data
  postgres_data:
    name: aestelo_db
  redis-insight:
    name: aestelo_redis-insight
