packages:
  - "apps/*"
  - "packages/*"
  - "backend"

publicHoistPattern:
  - 'uniwind'

allowBuilds:
  '@shopify/react-native-skia': true

minimumReleaseAgeExclude:
  - '@expo/cli@56.1.16'
  - '@expo/config-plugins@56.0.9'
  - '@expo/config-types@56.0.6'
  - '@expo/inline-modules@0.0.12'
  - '@expo/prebuild-config@56.0.16'
  - '@expo/ui@56.0.18'
  - expo-font@56.0.7
  - expo-image-picker@56.0.18
  - expo-location@56.0.18
  - expo-modules-autolinking@56.0.16
  - expo-modules-core@56.0.17
  - expo-modules-jsi@56.0.10
  - expo-notifications@56.0.18
  - expo-router@56.2.11
  - expo@56.0.12
  
overrides:
  'vue': 'beta'
  '@vue/compiler-core': 'beta'
  '@vue/compiler-dom': 'beta'
  '@vue/compiler-sfc': 'beta'
  '@vue/compiler-ssr': 'beta'
  '@vue/compiler-vapor': 'beta'
  '@vue/reactivity': 'beta'
  '@vue/runtime-core': 'beta'
  '@vue/runtime-dom': 'beta'
  '@vue/runtime-vapor': 'beta'
  '@vue/server-renderer': 'beta'
  '@vue/shared': 'beta'
  '@vue/compat': 'beta'

peerDependencyRules:
  allowAny:
    - 'vue'
