"""Change column names

Revision ID: 00316803a051
Revises: 3c1cc1bcd147
Create Date: 2026-01-09 00:02:49.979473

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '00316803a051'
down_revision = '3c1cc1bcd147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_id', sa.BigInteger(), nullable=False))
        batch_op.drop_index(batch_op.f('idx_rating_post_id'))
        batch_op.drop_constraint(batch_op.f('unique_rating'), type_='unique')
        batch_op.create_unique_constraint('unique_rating', ['user_profile_id', 'spot_id'])
        batch_op.create_index('idx_rating_spot_id', ['spot_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_rating_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rating_spot_id_spot'), 'spot', ['spot_id'], ['id'])
        batch_op.drop_column('post_id')

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_post_coordinates'), postgresql_using='gist')
        batch_op.create_index('idx_spot_coordinates', ['coordinates'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_id', sa.BigInteger(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_id'))
        batch_op.create_index(batch_op.f('ix_spot_id'), ['spot_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_post_media_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_spot_media_spot_id_spot'), 'spot', ['spot_id'], ['id'])
        batch_op.drop_column('post_id')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_count', sa.Integer(), nullable=True))
        batch_op.drop_column('post_count')

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot_id', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_visit_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_spot_id_spot'), 'spot', ['spot_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_visit_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_post_id_post'), 'spot', ['post_id'], ['id'])
        batch_op.drop_column('spot_id')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('spot_count')

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_spot_media_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_media_post_id_post'), 'spot', ['post_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_spot_id'))
        batch_op.create_index(batch_op.f('ix_post_id'), ['post_id'], unique=False)
        batch_op.drop_column('spot_id')

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.drop_index('idx_spot_coordinates', postgresql_using='gist')
        batch_op.create_index(batch_op.f('idx_post_coordinates'), ['coordinates'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_rating_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rating_post_id_post'), 'spot', ['post_id'], ['id'])
        batch_op.drop_index('idx_rating_spot_id')
        batch_op.drop_constraint('unique_rating', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_rating'), ['user_profile_id', 'post_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_rating_post_id'), ['post_id'], unique=False)
        batch_op.drop_column('spot_id')

    # ### end Alembic commands ###
