"""unique & indexes in collection, block, and rating. check constraint in rating model added

Revision ID: 80d70173a012
Revises: 5ed24d28a06c
Create Date: 2026-01-22 08:40:56.178521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d70173a012'
down_revision = '5ed24d28a06c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('block_profile_unique'), type_='unique')
        batch_op.drop_index(batch_op.f('idx_block_profile_blocker_id_blocked_id'))
        batch_op.create_index(batch_op.f('ix_block_profile_blocker_id_blocked_id'), ['blocker_id', 'blocked_id'], unique=True)

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_collection_user_id_name'), ['user_id', 'name'])

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_collection_item_collection_id_spot_id'), ['collection_id', 'spot_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_collection_item_collection_id_visit_id'), ['collection_id', 'visit_id'])

    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_follow_follower_id_following_id'))
        batch_op.drop_constraint(batch_op.f('unique_follow'), type_='unique')
        batch_op.create_index(batch_op.f('ix_follow_follower_id_following_id'), ['follower_id', 'following_id'], unique=True)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_rating'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_rating_user_id_spot_id'), ['user_id', 'spot_id'])
        batch_op.create_check_constraint(
        "rating_range",                
        "rating_choice >= 1 AND rating_choice <= 5"  
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_rating_user_id_spot_id'), type_='unique')
        batch_op.drop_constraint("rating_range", type_="check")
        batch_op.create_unique_constraint(batch_op.f('unique_rating'), ['user_id', 'spot_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follow_follower_id_following_id'))
        batch_op.create_unique_constraint(batch_op.f('unique_follow'), ['follower_id', 'following_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_follow_follower_id_following_id'), ['follower_id', 'following_id'], unique=False)

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_collection_item_collection_id_visit_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_collection_item_collection_id_spot_id'), type_='unique')

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_collection_user_id_name'), type_='unique')

    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_block_profile_blocker_id_blocked_id'))
        batch_op.create_index(batch_op.f('idx_block_profile_blocker_id_blocked_id'), ['blocker_id', 'blocked_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('block_profile_unique'), ['blocker_id', 'blocked_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
