"""added thumbnail column for colletions

Revision ID: a6e819dc7e98
Revises: bff2c1b41f8b
Create Date: 2026-01-23 23:14:34.937499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e819dc7e98'
down_revision = 'bff2c1b41f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_thumbnails', sa.ARRAY(sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('preview_thumbnails')

    # ### end Alembic commands ###
