"""db level cascade deletion for fk(s)

Revision ID: 4a6f91b7f27e
Revises: a6e819dc7e98
Create Date: 2026-01-24 04:45:48.320711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6f91b7f27e'
down_revision = 'a6e819dc7e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collection_user_id_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_collection_user_id_user_profile'), 'user_profile', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collection_item_visit_id_visit'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_collection_item_collection_id_collection'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_collection_item_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_collection_item_spot_id_spot'), 'spot', ['spot_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_collection_item_collection_id_collection'), 'collection', ['collection_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_collection_item_visit_id_visit'), 'visit', ['visit_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rating_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rating_spot_id_spot'), 'spot', ['spot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_spot_media_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_spot_media_spot_id_spot'), 'spot', ['spot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_media_visit_id_visit'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_media_visit_id_visit'), 'visit', ['visit_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_media_visit_id_visit'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_media_visit_id_visit'), 'visit', ['visit_id'], ['id'])

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_spot_media_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_spot_media_spot_id_spot'), 'spot', ['spot_id'], ['id'])

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rating_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rating_spot_id_spot'), 'spot', ['spot_id'], ['id'])

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collection_item_visit_id_visit'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_collection_item_collection_id_collection'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_collection_item_spot_id_spot'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_collection_item_spot_id_spot'), 'spot', ['spot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_collection_item_collection_id_collection'), 'collection', ['collection_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_collection_item_visit_id_visit'), 'visit', ['visit_id'], ['id'])

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collection_user_id_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_collection_user_id_user_profile'), 'user_profile', ['user_id'], ['id'])

    # ### end Alembic commands ###
