"""Initial migration

Revision ID: 2b8d2ebdc9c1
Revises: 
Create Date: 2025-12-13 23:09:55.742056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b8d2ebdc9c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_encrypted', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('email_change_sent_at', sa.DateTime(), nullable=True),
    sa.Column('password_change_sent_at', sa.DateTime(), nullable=True),
    sa.Column('password_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_user')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_auth_user_username')),
    schema='private'
    )
    op.create_table('token_black_list',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_black_list')),
    schema='private'
    )
    op.create_table('report',
    sa.Column('report_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_type', sa.String(length=20), nullable=False),
    sa.Column('reported_id', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['public.user_profile.id'], name=op.f('fk_report_reporter_id_user_profile')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_report')),
    sa.UniqueConstraint('reporter_id', 'reported_type', 'reported_id', name='unique_report'),
    schema='private'
    )
    with op.batch_alter_table('report', schema='private') as batch_op:
        batch_op.create_index('idx_report_item', ['reported_type', 'reported_id'], unique=False)
        batch_op.create_index('idx_report_status', ['status'], unique=False)

    op.create_table('user_info',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('height_ft', sa.Integer(), nullable=True),
    sa.Column('height_in', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['public.user_profile.id'], name=op.f('fk_user_info_user_profile_id_user_profile')),
    sa.PrimaryKeyConstraint('user_profile_id', name=op.f('pk_user_info')),
    schema='private'
    )
    op.create_table('user_role',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_moderator', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['public.user_profile.id'], name=op.f('fk_user_role_user_profile_id_user_profile')),
    sa.PrimaryKeyConstraint('user_profile_id', name=op.f('pk_user_role')),
    schema='private'
    )
    op.create_table('user_settings',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('language_preference', sa.String(length=50), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('location_sharing', sa.Boolean(), nullable=True),
    sa.Column('data_usage_consent', sa.Boolean(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('theme_preference', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['public.user_profile.id'], name=op.f('fk_user_settings_user_profile_id_user_profile')),
    sa.PrimaryKeyConstraint('user_profile_id', name=op.f('pk_user_settings')),
    schema='private'
    )
    op.create_table('user_subscription',
    sa.Column('user_profile_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('payment_method_id', sa.UUID(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=10), nullable=True),
    sa.Column('trial_used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['public.user_profile.id'], name=op.f('fk_user_subscription_user_profile_id_user_profile')),
    sa.PrimaryKeyConstraint('user_profile_id', name=op.f('pk_user_subscription')),
    schema='private'
    )
    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('block_profile_blocker_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('block_profile_blocked_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_block_profile_blocked_id_user_profile'), 'user_profile', ['blocked_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_block_profile_blocker_id_user_profile'), 'user_profile', ['blocker_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('businesss_location_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('businesss_location_details_location_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_businesss_location_details_location_id_location'), 'location', ['location_id'], ['location_id'], referent_schema='public')

    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('follow_following_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('follow_follower_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_follow_follower_id_user_profile'), 'user_profile', ['follower_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_follow_following_id_user_profile'), 'user_profile', ['following_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_location_post_media_id'))
        batch_op.drop_index(batch_op.f('ix_public_location_visit_media_id'))
        batch_op.create_index(batch_op.f('ix_post_media_id'), ['post_media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_media_id'), ['visit_media_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('location_visit_media_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('location_post_media_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_location_visit_media_id_visit_media'), 'visit_media', ['visit_media_id'], ['visit_media_id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_location_post_media_id_post_media'), 'post_media', ['post_media_id'], ['post_media_id'], referent_schema='public')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_post_user_profile_id'))
        batch_op.create_index(batch_op.f('ix_user_profile_id'), ['user_profile_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('post_user_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_user_profile_id_user_profile'), 'user_profile', ['user_profile_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_post_media_post_id'))
        batch_op.drop_index(batch_op.f('ix_public_post_media_uploaded_by'))
        batch_op.create_index(batch_op.f('ix_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.drop_constraint(batch_op.f('post_media_post_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('post_media_uploaded_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_post_media_uploaded_by_user_profile'), 'user_profile', ['uploaded_by'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_post_media_post_id_post'), 'post', ['post_id'], ['post_id'], referent_schema='public')

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('rating_user_profile_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('rating_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rating_user_profile_id_user_profile'), 'user_profile', ['user_profile_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_rating_post_id_post'), 'post', ['post_id'], ['post_id'], referent_schema='public')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_user_profile_music_track_id'))
        batch_op.create_index(batch_op.f('ix_music_track_id'), ['music_track_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('user_profile_music_track_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('user_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_profile_id_auth_user'), 'auth_user', ['id'], ['id'], referent_schema='private')
        batch_op.create_foreign_key(batch_op.f('fk_user_profile_music_track_id_music_track'), 'music_track', ['music_track_id'], ['music_track_id'], referent_schema='public')

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_visit_music_track_id'))
        batch_op.drop_index(batch_op.f('ix_public_visit_post_id'))
        batch_op.drop_index(batch_op.f('ix_public_visit_user_profile_id'))
        batch_op.create_index(batch_op.f('ix_music_track_id'), ['music_track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_id'), ['user_profile_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('visit_music_track_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visit_user_profile_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visit_post_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_post_id_post'), 'post', ['post_id'], ['post_id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_visit_music_track_id_music_track'), 'music_track', ['music_track_id'], ['music_track_id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_visit_user_profile_id_user_profile'), 'user_profile', ['user_profile_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_visit_media_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_public_visit_media_visit_id'))
        batch_op.create_index(batch_op.f('ix_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_id'), ['visit_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('visit_media_visit_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visit_media_uploaded_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_visit_media_uploaded_by_user_profile'), 'user_profile', ['uploaded_by'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(batch_op.f('fk_visit_media_visit_id_visit'), 'visit', ['visit_id'], ['visit_id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_media_visit_id_visit'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_visit_media_uploaded_by_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('visit_media_uploaded_by_fkey'), 'user_profile', ['uploaded_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('visit_media_visit_id_fkey'), 'visit', ['visit_id'], ['visit_id'])
        batch_op.drop_index(batch_op.f('ix_visit_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_by'))
        batch_op.create_index(batch_op.f('ix_public_visit_media_visit_id'), ['visit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_visit_media_uploaded_by'), ['uploaded_by'], unique=False)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_visit_user_profile_id_user_profile'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_visit_music_track_id_music_track'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_visit_post_id_post'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('visit_post_id_fkey'), 'post', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(batch_op.f('visit_user_profile_id_fkey'), 'user_profile', ['user_profile_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('visit_music_track_id_fkey'), 'music_track', ['music_track_id'], ['music_track_id'])
        batch_op.drop_index(batch_op.f('ix_user_profile_id'))
        batch_op.drop_index(batch_op.f('ix_post_id'))
        batch_op.drop_index(batch_op.f('ix_music_track_id'))
        batch_op.create_index(batch_op.f('ix_public_visit_user_profile_id'), ['user_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_visit_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_visit_music_track_id'), ['music_track_id'], unique=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_profile_music_track_id_music_track'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_user_profile_id_auth_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_profile_id_fkey'), 'auth_user', ['id'], ['id'], referent_schema='private')
        batch_op.create_foreign_key(batch_op.f('user_profile_music_track_id_fkey'), 'music_track', ['music_track_id'], ['music_track_id'])
        batch_op.drop_index(batch_op.f('ix_music_track_id'))
        batch_op.create_index(batch_op.f('ix_public_user_profile_music_track_id'), ['music_track_id'], unique=False)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rating_post_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_rating_user_profile_id_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rating_post_id_fkey'), 'post', ['post_id'], ['post_id'])
        batch_op.create_foreign_key(batch_op.f('rating_user_profile_id_fkey'), 'user_profile', ['user_profile_id'], ['id'])

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_media_post_id_post'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_post_media_uploaded_by_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_media_uploaded_by_fkey'), 'user_profile', ['uploaded_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('post_media_post_id_fkey'), 'post', ['post_id'], ['post_id'])
        batch_op.drop_index(batch_op.f('ix_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_post_id'))
        batch_op.create_index(batch_op.f('ix_public_post_media_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_post_media_post_id'), ['post_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_post_user_profile_id_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('post_user_profile_id_fkey'), 'user_profile', ['user_profile_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_user_profile_id'))
        batch_op.create_index(batch_op.f('ix_public_post_user_profile_id'), ['user_profile_id'], unique=False)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_location_post_media_id_post_media'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_location_visit_media_id_visit_media'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('location_post_media_id_fkey'), 'post_media', ['post_media_id'], ['post_media_id'])
        batch_op.create_foreign_key(batch_op.f('location_visit_media_id_fkey'), 'visit_media', ['visit_media_id'], ['visit_media_id'])
        batch_op.drop_index(batch_op.f('ix_visit_media_id'))
        batch_op.drop_index(batch_op.f('ix_post_media_id'))
        batch_op.create_index(batch_op.f('ix_public_location_visit_media_id'), ['visit_media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_public_location_post_media_id'), ['post_media_id'], unique=False)

    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_follow_following_id_user_profile'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_follow_follower_id_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('follow_follower_id_fkey'), 'user_profile', ['follower_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('follow_following_id_fkey'), 'user_profile', ['following_id'], ['id'])

    with op.batch_alter_table('businesss_location_details', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_businesss_location_details_location_id_location'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('businesss_location_details_location_id_fkey'), 'location', ['location_id'], ['location_id'])

    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_block_profile_blocker_id_user_profile'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_block_profile_blocked_id_user_profile'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('block_profile_blocked_id_fkey'), 'user_profile', ['blocked_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('block_profile_blocker_id_fkey'), 'user_profile', ['blocker_id'], ['id'])

    op.drop_table('user_subscription', schema='private')
    op.drop_table('user_settings', schema='private')
    op.drop_table('user_role', schema='private')
    op.drop_table('user_info', schema='private')
    with op.batch_alter_table('report', schema='private') as batch_op:
        batch_op.drop_index('idx_report_status')
        batch_op.drop_index('idx_report_item')

    op.drop_table('report', schema='private')
    op.drop_table('token_black_list', schema='private')
    op.drop_table('auth_user', schema='private')
    # ### end Alembic commands ###
