"""Removed location table and uneccesary colums from post and post media table

Revision ID: 41d3a52f90ed
Revises: 6815821fedec
Create Date: 2026-01-01 03:31:49.796497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '41d3a52f90ed'
down_revision = '6815821fedec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_location_details')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_location_coords'))
        batch_op.drop_index(batch_op.f('ix_post_media_id'))
        batch_op.drop_index(batch_op.f('ix_visit_media_id'))

    op.drop_table('location')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
        batch_op.drop_column('refined_location')

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.Text(), nullable=True))
        batch_op.drop_column('is_primary')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('index')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('thumb_media_type')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=150),
               existing_nullable=True)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True))
        batch_op.drop_column('refined_location')

    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photo_path', sa.Text(), nullable=True))
        batch_op.drop_column('is_primary')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('index')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('thumb_media_type')
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thumb_media_type', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_path')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refined_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_visit_coordinates', postgresql_using='gist')
        batch_op.drop_column('coordinates')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('post_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_media_type', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('photo_path')
        batch_op.drop_column('sort_order')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refined_location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_post_coordinates', postgresql_using='gist')
        batch_op.drop_column('coordinates')

    op.create_table('location',
    sa.Column('post_media_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('visit_media_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('location_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('altitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_media_id'], ['post_media.id'], name='fk_location_post_media_id_post_media'),
    sa.ForeignKeyConstraint(['visit_media_id'], ['visit_media.id'], name='fk_location_visit_media_id_visit_media'),
    sa.PrimaryKeyConstraint('id', name='pk_location'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_media_id'), ['visit_media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_media_id'), ['post_media_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_location_coords'), ['latitude', 'longitude'], unique=False)

    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('business_location_details',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('address_line1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address_line2', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('fk_business_location_details_location_id_location')),
    sa.PrimaryKeyConstraint('location_id', name=op.f('pk_business_location_details'))
    )
    # ### end Alembic commands ###
