"""added index to data posted col for Spot model

Revision ID: 4f3c22367d8c
Revises: bc0585f4734d
Create Date: 2026-01-20 00:31:33.862924

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '4f3c22367d8c'
down_revision = 'bc0585f4734d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_date_posted'), ['date_posted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_date_posted'))

    # ### end Alembic commands ###
