"""type hint updates and index changes

Revision ID: 5679238f3200
Revises: a8227ae8e048
Create Date: 2026-01-22 05:12:43.386813

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5679238f3200'
down_revision = 'a8227ae8e048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_block_user_blocked'))
        batch_op.drop_index(batch_op.f('idx_block_user_blocker_blocked'))
        batch_op.create_index('idx_block_profile_blocker_id_blocked_id', ['blocker_id', 'blocked_id'], unique=False)

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.alter_column('collection_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_follow_follower'))
        batch_op.drop_index(batch_op.f('idx_follow_following'))
        batch_op.create_index('idx_follow_follower_id_following_id', ['follower_id', 'following_id'], unique=False)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('rating_choice',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('idx_rating_spot_id'))
        batch_op.drop_column('rating_id')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('coordinates',
               existing_type=Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               nullable=False)
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('total_num_of_photos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('visit_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('total_num_of_ratings',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('save_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('share_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('accessibility',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('num_of_edits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('num_reports',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_removed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('last_rated_at')

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.alter_column('spot_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('sort_order',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('photo_path',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('photo_type',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('token_black_list', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('height_ft',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('height_in',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('is_verified_instagram',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_verified_facebook',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_verified_twitter_x',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_verified_tiktok',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('spot_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('visit_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('follower_count',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('following_count',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('show_online_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_business_account',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_prem_account',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('num_reports_made',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('num_reports',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('profile_created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('push_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('location_sharing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('data_usage_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('theme_preference',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('billing_cycle',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('like_count',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('save_count',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('share_count',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('num_of_edits',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('num_reports',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_removed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.alter_column('photo_type',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.alter_column('photo_type',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('is_removed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('num_reports',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('num_of_edits',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('share_count',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('save_count',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('like_count',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.alter_column('trial_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('billing_cycle',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('theme_preference',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('marketing_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('data_usage_consent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('location_sharing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('push_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email_notifications',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('user_role', schema=None) as batch_op:
        batch_op.alter_column('is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('profile_created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('num_reports',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('num_reports_made',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_prem_account',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_business_account',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('show_online_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('following_count',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('follower_count',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('visit_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('spot_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_verified_tiktok',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_verified_twitter_x',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_verified_facebook',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_verified_instagram',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('height_in',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('height_ft',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('token_black_list', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.alter_column('photo_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('photo_path',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('sort_order',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('uploaded_by',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('spot_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_rated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('is_removed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('num_reports',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('num_of_edits',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('accessibility',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('share_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('save_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_num_of_ratings',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('average_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('visit_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_num_of_photos',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date_posted',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('coordinates',
               existing_type=Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', _spatial_index_reflected=True),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_id', sa.BIGINT(), autoincrement=True, nullable=False))
        batch_op.create_index(batch_op.f('idx_rating_spot_id'), ['spot_id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('rating_choice',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index('idx_follow_follower_id_following_id')
        batch_op.create_index(batch_op.f('idx_follow_following'), ['following_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_follow_follower'), ['follower_id'], unique=False)

    with op.batch_alter_table('collection_item', schema=None) as batch_op:
        batch_op.alter_column('saved_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('collection_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.drop_index('idx_block_profile_blocker_id_blocked_id')
        batch_op.create_index(batch_op.f('idx_block_user_blocker_blocked'), ['blocker_id', 'blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_block_user_blocked'), ['blocked_id'], unique=False)

    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.alter_column('email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
