"""initial migration

Revision ID: 5ed24d28a06c
Revises: 
Create Date: 2026-01-22 07:07:55.786288

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ed24d28a06c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_encrypted', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('email_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_change_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_change_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_user')),
    sa.UniqueConstraint('email', name=op.f('uq_auth_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_auth_user_username'))
    )
    op.create_table('music_track',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('track_name', sa.String(length=200), nullable=False),
    sa.Column('artist_name', sa.String(length=200), nullable=False),
    sa.Column('album_name', sa.String(length=200), nullable=True),
    sa.Column('album_art_url', sa.String(length=500), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('music_url', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('duration_formatted', sa.String(length=10), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_music_track'))
    )
    op.create_table('token_black_list',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_black_list'))
    )
    with op.batch_alter_table('token_black_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_black_list_jti'), ['jti'], unique=False)

    op.create_table('user_profile',
    sa.Column('music_track_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('profile_photo', sa.Text(), nullable=True),
    sa.Column('profile_banner', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('is_verified_instagram', sa.Boolean(), nullable=False),
    sa.Column('facebook', sa.Text(), nullable=True),
    sa.Column('is_verified_facebook', sa.Boolean(), nullable=False),
    sa.Column('twitter_x', sa.Text(), nullable=True),
    sa.Column('is_verified_twitter_x', sa.Boolean(), nullable=False),
    sa.Column('tiktok', sa.Text(), nullable=True),
    sa.Column('is_verified_tiktok', sa.Boolean(), nullable=False),
    sa.Column('spot_count', sa.Integer(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('follower_count', sa.BigInteger(), nullable=False),
    sa.Column('following_count', sa.BigInteger(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('show_online_status', sa.Boolean(), nullable=False),
    sa.Column('is_business_account', sa.Boolean(), nullable=False),
    sa.Column('is_prem_account', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('banned_reason', sa.Text(), nullable=True),
    sa.Column('banned_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_reports_made', sa.Integer(), nullable=False),
    sa.Column('num_reports', sa.Integer(), nullable=False),
    sa.Column('profile_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth_user.id'], name=op.f('fk_user_profile_id_auth_user')),
    sa.ForeignKeyConstraint(['music_track_id'], ['music_track.id'], name=op.f('fk_user_profile_music_track_id_music_track')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    op.create_table('block_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('blocker_id', sa.UUID(), nullable=False),
    sa.Column('blocked_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['user_profile.id'], name=op.f('fk_block_profile_blocked_id_user_profile')),
    sa.ForeignKeyConstraint(['blocker_id'], ['user_profile.id'], name=op.f('fk_block_profile_blocker_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_block_profile')),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='block_profile_unique')
    )
    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.create_index('idx_block_profile_blocker_id_blocked_id', ['blocker_id', 'blocked_id'], unique=False)

    op.create_table('collection',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_collection_user_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection'))
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_user_id'), ['user_id'], unique=False)

    op.create_table('follow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user_profile.id'], name=op.f('fk_follow_follower_id_user_profile')),
    sa.ForeignKeyConstraint(['following_id'], ['user_profile.id'], name=op.f('fk_follow_following_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow')),
    sa.UniqueConstraint('follower_id', 'following_id', name='unique_follow')
    )
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.create_index('idx_follow_follower_id_following_id', ['follower_id', 'following_id'], unique=False)

    op.create_table('report',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_type', sa.Text(), nullable=False),
    sa.Column('reported_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user_profile.id'], name=op.f('fk_report_reporter_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    op.create_geospatial_table('spot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('coordinates', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_num_of_photos', sa.Integer(), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('total_num_of_ratings', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('accessibility', sa.Boolean(), nullable=False),
    sa.Column('num_of_edits', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_reports', sa.Integer(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_spot_user_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spot'))
    )
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_spot_coordinates', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
        batch_op.create_index(batch_op.f('ix_spot_date_posted'), ['date_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_spot_user_id'), ['user_id'], unique=False)

    op.create_table('user_info',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Text(), nullable=False),
    sa.Column('height_ft', sa.Integer(), nullable=False),
    sa.Column('height_in', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_user_info_user_id_user_profile')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_info'))
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_moderator', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_user_role_user_id_user_profile')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_role'))
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language_preference', sa.Text(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('location_sharing', sa.Boolean(), nullable=False),
    sa.Column('data_usage_consent', sa.Boolean(), nullable=False),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('theme_preference', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_user_settings_user_id_user_profile')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_settings'))
    )
    op.create_table('user_subscription',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('payment_method_id', sa.Uuid(), nullable=True),
    sa.Column('billing_cycle', sa.Text(), nullable=False),
    sa.Column('trial_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_user_subscription_user_id_user_profile')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_subscription'))
    )
    op.create_table('rating',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('spot_id', sa.BigInteger(), nullable=False),
    sa.Column('rating_choice', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], name=op.f('fk_rating_spot_id_spot')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_rating_user_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating')),
    sa.UniqueConstraint('user_id', 'spot_id', name='unique_rating')
    )
    op.create_table('spot_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('spot_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.BigInteger(), nullable=False),
    sa.Column('photo_path', sa.Text(), nullable=False),
    sa.Column('photo_type', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], name=op.f('fk_spot_media_spot_id_spot')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_profile.id'], name=op.f('fk_spot_media_uploaded_by_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spot_media'))
    )
    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spot_media_spot_id'), ['spot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spot_media_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_geospatial_table('visit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('spot_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coordinates', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('music_track_id', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('save_count', sa.BigInteger(), nullable=False),
    sa.Column('share_count', sa.BigInteger(), nullable=False),
    sa.Column('total_num_of_photos', sa.Integer(), nullable=True),
    sa.Column('num_of_edits', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('num_reports', sa.Integer(), nullable=False),
    sa.Column('is_removed', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['music_track_id'], ['music_track.id'], name=op.f('fk_visit_music_track_id_music_track')),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], name=op.f('fk_visit_spot_id_spot')),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_visit_user_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit'))
    )
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_geospatial_index('idx_visit_coordinates', ['coordinates'], unique=False, postgresql_using='gist', postgresql_ops={})
        batch_op.create_index(batch_op.f('ix_visit_user_id'), ['user_id'], unique=False)

    op.create_table('collection_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('spot_id', sa.BigInteger(), nullable=True),
    sa.Column('visit_id', sa.BigInteger(), nullable=True),
    sa.Column('saved_by', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_collection_item_collection_id_collection')),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], name=op.f('fk_collection_item_spot_id_spot')),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], name=op.f('fk_collection_item_visit_id_visit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_item'))
    )
    op.create_table('visit_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('photo_path', sa.Text(), nullable=True),
    sa.Column('photo_type', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user_profile.id'], name=op.f('fk_visit_media_uploaded_by_user_profile')),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], name=op.f('fk_visit_media_visit_id_visit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_media'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_media')
    op.drop_table('collection_item')
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_user_id'))
        batch_op.drop_geospatial_index('idx_visit_coordinates', postgresql_using='gist', column_name='coordinates')

    op.drop_geospatial_table('visit')
    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spot_media_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_spot_media_spot_id'))

    op.drop_table('spot_media')
    op.drop_table('rating')
    op.drop_table('user_subscription')
    op.drop_table('user_settings')
    op.drop_table('user_role')
    op.drop_table('user_info')
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spot_user_id'))
        batch_op.drop_index(batch_op.f('ix_spot_date_posted'))
        batch_op.drop_geospatial_index('idx_spot_coordinates', postgresql_using='gist', column_name='coordinates')

    op.drop_geospatial_table('spot')
    op.drop_table('report')
    with op.batch_alter_table('follow', schema=None) as batch_op:
        batch_op.drop_index('idx_follow_follower_id_following_id')

    op.drop_table('follow')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_user_id'))

    op.drop_table('collection')
    with op.batch_alter_table('block_profile', schema=None) as batch_op:
        batch_op.drop_index('idx_block_profile_blocker_id_blocked_id')

    op.drop_table('block_profile')
    op.drop_table('user_profile')
    with op.batch_alter_table('token_black_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_black_list_jti'))

    op.drop_table('token_black_list')
    op.drop_table('music_track')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
