"""added visit count to Spot

Revision ID: 5eee2fc37614
Revises: 00316803a051
Create Date: 2026-01-14 03:49:29.226615

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '5eee2fc37614'
down_revision = '00316803a051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.drop_column('visit_count')

    # ### end Alembic commands ###
