"""updated string cols to Text. Added collection and collection item models

Revision ID: 607e7383b1dc
Revises: 73af2305e8e8
Create Date: 2026-01-20 01:53:55.250011

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '607e7383b1dc'
down_revision = '73af2305e8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], name=op.f('fk_collection_user_id_user_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection'))
    )
    op.create_table('collection_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('spot_id', sa.BigInteger(), nullable=True),
    sa.Column('visit_id', sa.BigInteger(), nullable=True),
    sa.Column('saved_by', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], name=op.f('fk_collection_item_collection_id_collection')),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], name=op.f('fk_collection_item_spot_id_spot')),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], name=op.f('fk_collection_item_visit_id_visit')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_item'))
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('reported_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('reported_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.UUID(),
               postgresql_using='reported_id::uuid',
               existing_nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.alter_column('photo_type',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('music_track_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('bio',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('banner_theme')

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('language_preference',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('billing_cycle',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('music_track_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('caption',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.alter_column('photo_type',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit_media', schema=None) as batch_op:
        batch_op.alter_column('photo_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('caption',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('music_track_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user_subscription', schema=None) as batch_op:
        batch_op.alter_column('billing_cycle',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column('language_preference',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_theme', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.alter_column('bio',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('music_track_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.alter_column('city',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('spot_media', schema=None) as batch_op:
        batch_op.alter_column('photo_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    with op.batch_alter_table('spot', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('reported_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('reported_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.drop_table('collection_item')
    op.drop_table('collection')
    # ### end Alembic commands ###
